version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - store_artifacts:
          path: coverage
          destination: coverage

      - run: npm install vercel@latest
     
      - run: npx vercel pull --yes --environment=preview --token=${VERCEL_TOKEN}
      - run: npx vercel build --token=${VERCEL_TOKEN}
      - run: npx vercel deploy --prebuilt --token=${VERCEL_TOKEN}
          
      # - run: npm coveralls
      # - run: npm run build
      # - name: Install Vercel CLI
      #   run: npm install --global vercel@latest
      # - name: Pull Vercel Environment Information
      #   run: vercel pull --yes --environment=preview --token=
      # - name: Build Project Artifacts
      #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Deploy Project Artifacts to Vercel
      #   run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
workflows:
  build-and-test:
    jobs:
      - test
